name: pacs
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=3=2_zen
  - absl-py=2.2.0=pyhd8ed1ab_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - contourpy=1.3.1=py312h68727a3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - deepxde=1.14.0=pyh46bd161_0
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.0=h5888daf_0
  - flatbuffers=25.2.10=hb7832b1_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py312h178313f_0
  - freetype=2.13.3=h48d6fc4_0
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.73.1=py312h6f3464c_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - harfbuzz=11.0.1=h2c12942_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - keras=3.9.0=pyh753f3f9_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.2=default_hb5137d0_0
  - libclang13=20.1.2=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.16.0=h4e3cde8_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm20=20.1.2=ha7bfdaf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libml_dtypes-headers=0.5.3=h707e725_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.4=h27ae623_1
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.08.12=h7b12aa8_1
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtensorflow_cc=2.19.1=cpu_h3deb7bb_50
  - libtensorflow_framework=2.19.1=cpu_h18e7061_50
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.1=hc4a0caf_0
  - libxml2=2.13.7=h4bc477f_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.10.1=py312h7900ff3_0
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ml_dtypes=0.5.1=py312hf79963d_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.2.0=h266115a_0
  - mysql-libs=9.2.0=he0572af_0
  - namex=0.0.8=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.15.0=py312h68727a3_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.3.3=py312hf79963d_1
  - pcre2=10.44=hba22ea6_2
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - protobuf=6.31.1=py312hb8af0ac_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyaml=25.1.0=pyhd8ed1ab_0
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py312h91f0f75_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=6_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_1
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - scikit-learn=1.4.2=py312h1fcc3ea_1
  - scikit-optimize=0.10.2=pyhd8ed1ab_0
  - scipy=1.15.2=py312ha707e6e_0
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_0
  - tensorboard=2.19.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py312hda17c39_2
  - tensorflow-base=2.19.1=cpu_py312h486b088_50
  - tensorflow-estimator=2.19.1=cpu_py312ha43043b_50
  - termcolor=3.0.1=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py312h66e93f0_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py312h66e93f0_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py312h66e93f0_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - attrs==25.3.0
      - cloudpickle==3.1.1
      - decorator==5.2.1
      - dm-tree==0.1.9
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - libclang==18.1.1
      - mpmath==1.3.0
      - networkx==3.3
      - sympy==1.13.3
      - tensorflow==2.19.0
      - tensorflow-probability==0.25.0
      - tf-keras==2.19.0
      - torch==2.7.0+cpu
      - torchaudio==2.7.0+cpu
      - torchvision==0.22.0+cpu
prefix: /home/paolo/miniforge3/envs/pacs
